transacoes:
  events: "coffeeandit-sse"
  duration: 2

limites:
  url: http://localhost:8081

transaction:
  url: http://localhost:8082

spring:
  redis:
    port: 6379
    host: localhost
    timeout: 5000
  kafka:
    bootstrap-servers: localhost:9092